/**
 * Computes a structural perplexity proxy (entropy score) over the token distribution.
 * 
 * In a full heavy-weight system, this would evaluate the true log-likelihoods 
 * generated by a local LLM over these tokens. For standalone static analysis, 
 * we estimate n-gram/unigram Shannon entropy to detect repetitive or 
 * highly predictable token distributions common in AI text.
 */
export function calculatePerplexity(tokens: string[] | number[]): number {
  if (tokens.length === 0) return 0;
  
  // Calculate unigram frequencies
  const frequencies = new Map<string | number, number>();
  for (const token of tokens) {
    frequencies.set(token, (frequencies.get(token) || 0) + 1);
  }
  
  // Calculate Shannon entropy (H = -sum(p * log(p)))
  let entropy = 0;
  const total = tokens.length;
  for (const count of frequencies.values()) {
    const p = count / total;
    entropy -= p * Math.log2(p);
  }
  
  // Perplexity = 2 ^ Entropy
  return Math.pow(2, entropy);
}

/**
 * Computes burstiness by analyzing the standard deviation of sentence lengths.
 * High burstiness (varying sentence lengths) generally correlates with human writing.
 * Low burstiness (uniform sentence lengths) frequently points to LLM generation.
 */
export function calculateBurstiness(text: string): number {
  if (!text || !text.trim()) return 0;

  // Split into sentences using common punctuation boundaries
  const sentences = text
    .split(/[.!?]+(?:\s+|$)/)
    .map(s => s.trim())
    .filter(s => s.length > 0);
    
  if (sentences.length === 0) return 0;

  const lengths = sentences.map(s => s.split(/\s+/).length);

  const sum = lengths.reduce((acc, val) => acc + val, 0);
  const mean = sum / lengths.length;

  if (lengths.length === 1) return 0; // Standard deviation of a single sample is 0

  // Sample variance
  const variance = lengths.reduce((acc, val) => acc + Math.pow(val - mean, 2), 0) / (lengths.length - 1);
  
  return Math.sqrt(variance);
}
